'use client'

import { Poppins } from "next/font/google";
import "@/styles/globals.scss";
// import ReduxProvider from "@/store/redux-provider";
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/lib/integration/react';
import { store, persistor } from '../store/store';

const poppins = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <ReduxProvider> */}
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <body className={poppins.className}>{children}</body>
        </PersistGate>
      </Provider>
      {/* </ReduxProvider> */}
    </html>
  );
}
